"""empty message

Revision ID: 18822c186730
Revises: dcedc597a7e0
Create Date: 2023-03-24 13:26:54.702272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18822c186730'
down_revision = 'dcedc597a7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('system_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('system_comment_timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_system_comment_timestamp')
        batch_op.create_index(batch_op.f('ix_system_comment_system_comment_timestamp'), ['system_comment_timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'system', ['system_id'], ['system_id'])
        batch_op.drop_column('what_system_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('system_comment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_comment_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('what_system_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_system_comment_system_comment_timestamp'))
        batch_op.create_index('ix_system_comment_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('system_comment_timestamp')
        batch_op.drop_column('system_id')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###
