"""empty message

Revision ID: 1a06c2b89036
Revises: 938eac2ce05a
Create Date: 2023-03-24 11:44:17.061018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a06c2b89036'
down_revision = '938eac2ce05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_comment_timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_system_comment_timestamp')
        batch_op.create_index(batch_op.f('ix_system_comment_system_comment_timestamp'), ['system_comment_timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'system', ['what_system_id'], ['system_id'])
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_system_comment_system_comment_timestamp'))
        batch_op.create_index('ix_system_comment_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('system_comment_timestamp')

    # ### end Alembic commands ###
