"""Added note

Revision ID: 2f969e63c179
Revises: 3b41a940bdf2
Create Date: 2023-09-18 08:33:02.899707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f969e63c179'
down_revision = '3b41a940bdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=160), nullable=True))

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=160), nullable=True))

    with op.batch_alter_table('soi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=160), nullable=True))

    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('soi', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
