"""empty message

Revision ID: 3de4ec54d5db
Revises: ff6e69f01ef5
Create Date: 2023-05-16 08:07:20.046828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de4ec54d5db'
down_revision = 'ff6e69f01ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_soi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_joint', sa.Integer(), nullable=True),
    sa.Column('soi_joint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['soi_joint'], ['soi.id'], ),
    sa.ForeignKeyConstraint(['system_joint'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_soi')
    # ### end Alembic commands ###
