"""Added note for todos

Revision ID: 56d98d6ae7b6
Revises: 2f969e63c179
Create Date: 2023-09-18 08:34:11.587549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d98d6ae7b6'
down_revision = '2f969e63c179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
