"""empty message

Revision ID: 5f0e243a91ff
Revises: 18822c186730
Create Date: 2023-03-24 13:28:12.158086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5f0e243a91ff"
down_revision = "18822c186730"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_comment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("comment_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("system_comment_timestamp", sa.DateTime(), nullable=True)
        )
        batch_op.drop_index("ix_system_comment_timestamp")
        batch_op.create_index(
            batch_op.f("ix_system_comment_system_comment_timestamp"),
            ["system_comment_timestamp"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "what_system_id", "system", ["what_system_id"], ["system_id"]
        )
        batch_op.drop_column("system_comment_id")
        batch_op.drop_column("timestamp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("system_comment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timestamp", sa.DATETIME(), nullable=True))
        batch_op.add_column(
            sa.Column("system_comment_id", sa.INTEGER(), nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_system_comment_system_comment_timestamp"))
        batch_op.create_index(
            "ix_system_comment_timestamp", ["timestamp"], unique=False
        )
        batch_op.drop_column("system_comment_timestamp")
        batch_op.drop_column("comment_id")

    # ### end Alembic commands ###
