"""empty message

Revision ID: 661ffbd311b4
Revises: 2d2a30818f8a
Create Date: 2023-09-12 10:10:13.943203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661ffbd311b4'
down_revision = '2d2a30818f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_group')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=160), nullable=False))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=160), nullable=False))
        batch_op.drop_column('name')

    op.create_table('_alembic_tmp_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('soi_id', sa.INTEGER(), nullable=True),
    sa.Column('component_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=160), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['soi_id'], ['soi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
