"""empty message

Revision ID: 860e37af2e23
Revises: 
Create Date: 2023-04-24 14:02:23.025720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860e37af2e23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=160), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('soi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=160), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=160), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('component_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=160), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['component.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('component_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_comment_timestamp'), ['timestamp'], unique=False)

    op.create_table('component_soi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_joint', sa.Integer(), nullable=True),
    sa.Column('soi_joint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comp_joint'], ['component.id'], ),
    sa.ForeignKeyConstraint(['soi_joint'], ['soi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soi_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=160), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['soi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('soi_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_soi_comment_timestamp'), ['timestamp'], unique=False)

    op.create_table('system_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=160), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_comment_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_comment_timestamp'))

    op.drop_table('system_comment')
    with op.batch_alter_table('soi_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soi_comment_timestamp'))

    op.drop_table('soi_comment')
    op.drop_table('component_soi')
    with op.batch_alter_table('component_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_comment_timestamp'))

    op.drop_table('component_comment')
    op.drop_table('system')
    op.drop_table('soi')
    op.drop_table('component')
    # ### end Alembic commands ###
