"""empty message

Revision ID: 8c57cb3689f2
Revises: b9df36a99e7f
Create Date: 2023-03-24 13:13:44.253008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c57cb3689f2"
down_revision = "b9df36a99e7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("systemcomment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("timestamp_sys_com", sa.DateTime(), nullable=True)
        )
        batch_op.drop_index("ix_system_comment_timestamp")
        batch_op.create_index(
            batch_op.f("ix_system_comment_timestamp_sys_com"),
            ["timestamp_sys_com"],
            unique=False,
        )
        batch_op.create_foreign_key(None, "system", ["what_system_id"], ["system_id"])
        batch_op.drop_column("timestamp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("systemcomment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timestamp", sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_system_comment_timestamp_sys_com"))
        batch_op.create_index(
            "ix_system_comment_timestamp", ["timestamp"], unique=False
        )
        batch_op.drop_column("timestamp_sys_com")

    # ### end Alembic commands ###
