"""empty message

Revision ID: a7afc2226989
Revises: 8fd1be7278ca
Create Date: 2023-09-12 11:36:38.162245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7afc2226989'
down_revision = '8fd1be7278ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('component_id')
        batch_op.drop_column('soi_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soi_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('component_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'soi', ['soi_id'], ['id'])
        batch_op.create_foreign_key(None, 'component', ['component_id'], ['id'])

    # ### end Alembic commands ###
