"""empty message

Revision ID: a9b44719bd8b
Revises: 3a488a70329b
Create Date: 2023-03-20 10:37:14.819125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b44719bd8b'
down_revision = '3a488a70329b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_Comment',
    sa.Column('component_comment_id', sa.Integer(), nullable=False),
    sa.Column('what_component_id', sa.Integer(), nullable=True),
    sa.Column('component_comment_text', sa.String(length=160), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['what_component_id'], ['component.component_id'], ),
    sa.PrimaryKeyConstraint('component_comment_id')
    )
    with op.batch_alter_table('component_Comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_component_Comment_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('component__comment', schema=None) as batch_op:
        batch_op.drop_index('ix_component__comment_timestamp')

    op.drop_table('component__comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component__comment',
    sa.Column('component_comment_id', sa.INTEGER(), nullable=False),
    sa.Column('what_component_id', sa.INTEGER(), nullable=True),
    sa.Column('component_comment_text', sa.VARCHAR(length=160), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['what_component_id'], ['component.component_id'], ),
    sa.PrimaryKeyConstraint('component_comment_id')
    )
    with op.batch_alter_table('component__comment', schema=None) as batch_op:
        batch_op.create_index('ix_component__comment_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('component_Comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_Comment_timestamp'))

    op.drop_table('component_Comment')
    # ### end Alembic commands ###
