"""empty message

Revision ID: c397c305ae13
Revises: ef036584878e
Create Date: 2023-03-29 13:52:44.155140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c397c305ae13'
down_revision = 'ef036584878e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_soi',
    sa.Column('comp_soi_id', sa.Integer(), nullable=False),
    sa.Column('what_comp_joint', sa.Integer(), nullable=True),
    sa.Column('what_soi_joint', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['what_comp_joint'], ['component.component_id'], ),
    sa.ForeignKeyConstraint(['what_soi_joint'], ['soi.soi_id'], ),
    sa.PrimaryKeyConstraint('comp_soi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_soi')
    # ### end Alembic commands ###
