"""change group name

Revision ID: c675102a8aaa
Revises: f3813444e405
Create Date: 2023-09-28 11:48:04.271896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c675102a8aaa'
down_revision = 'f3813444e405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=160), nullable=True),
    sa.Column('note', sa.String(length=160), nullable=True),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('group')
    with op.batch_alter_table('group_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'my_group', ['product_id'], ['id'])

    with op.batch_alter_table('group_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'my_group', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])

    with op.batch_alter_table('group_comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['product_id'], ['id'])

    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), nullable=False),
    sa.Column('status', sa.VARCHAR(length=160), nullable=True),
    sa.Column('check', sa.BOOLEAN(), nullable=True),
    sa.Column('note', sa.VARCHAR(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('my_group')
    # ### end Alembic commands ###
