"""empty message

Revision ID: e843ae7f7e17
Revises: 2f739641c546
Create Date: 2023-03-21 15:02:11.761670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e843ae7f7e17'
down_revision = '2f739641c546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soi_description', sa.String(length=160), nullable=True))
        batch_op.create_unique_constraint(None, ['soi_description'])

    with op.batch_alter_table('soi__comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_soi__comment_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'soi', ['what_soi_id'], ['soi_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soi__comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_soi__comment_timestamp'))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('soi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('soi_description')

    # ### end Alembic commands ###
