"""empty message

Revision ID: e8fb975846a0
Revises: 233518b48b6f
Create Date: 2023-03-24 11:35:37.487315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fb975846a0'
down_revision = '233518b48b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_status', sa.String(length=160), nullable=True))

    with op.batch_alter_table('system_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_system_comment_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_comment_timestamp'))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('system', schema=None) as batch_op:
        batch_op.drop_column('system_status')

    # ### end Alembic commands ###
