"""empty message

Revision ID: ee33cf255868
Revises: 4ed624079ab9
Create Date: 2023-09-12 11:30:45.113687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee33cf255868'
down_revision = '4ed624079ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=160), nullable=True),
    sa.Column('soi_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['soi_id'], ['soi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('soi_id')
        batch_op.drop_column('component_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('soi_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'component', ['component_id'], ['id'])
        batch_op.create_foreign_key(None, 'soi', ['soi_id'], ['id'])

    op.drop_table('group_product')
    # ### end Alembic commands ###
