"""empty message

Revision ID: f952848c8b03
Revises: 8b223bb9a735
Create Date: 2023-09-11 13:08:37.381381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f952848c8b03'
down_revision = '8b223bb9a735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=160), nullable=False),
    sa.Column('soi_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['soi_id'], ['soi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=16),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=6),
               nullable=True)

    op.drop_table('group')
    # ### end Alembic commands ###
