"""empty message

Revision ID: ff6e69f01ef5
Revises: ca500b5ac56c
Create Date: 2023-04-26 11:37:12.736265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6e69f01ef5'
down_revision = 'ca500b5ac56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_column('supplier')

    # ### end Alembic commands ###
